GET http://localhost:3000/teams

###

GET http://localhost:3000/teams/3

###

POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "Suns",
  "wins": 60,
  "loses": 20
}

###

PATCH http://localhost:3000/teams/1
Content-Type: application/json

{
  "name": "The Chicago Bulls"
}